// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/playerservice.proto

package go_micro_srv_playerservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Player struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	TeamId               int32    `protobuf:"varint,2,opt,name=TeamId,proto3" json:"TeamId,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Position             string   `protobuf:"bytes,4,opt,name=Position,proto3" json:"Position,omitempty"`
	Rating               int32    `protobuf:"varint,5,opt,name=Rating,proto3" json:"Rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerservice_320609145fc483eb, []int{0}
}
func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (dst *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(dst, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player) GetTeamId() int32 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *Player) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

type DraftPlayerRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TeamId               int32    `protobuf:"varint,2,opt,name=teamId,proto3" json:"teamId,omitempty"`
	Position             string   `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DraftPlayerRequest) Reset()         { *m = DraftPlayerRequest{} }
func (m *DraftPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*DraftPlayerRequest) ProtoMessage()    {}
func (*DraftPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerservice_320609145fc483eb, []int{1}
}
func (m *DraftPlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DraftPlayerRequest.Unmarshal(m, b)
}
func (m *DraftPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DraftPlayerRequest.Marshal(b, m, deterministic)
}
func (dst *DraftPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DraftPlayerRequest.Merge(dst, src)
}
func (m *DraftPlayerRequest) XXX_Size() int {
	return xxx_messageInfo_DraftPlayerRequest.Size(m)
}
func (m *DraftPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DraftPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DraftPlayerRequest proto.InternalMessageInfo

func (m *DraftPlayerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DraftPlayerRequest) GetTeamId() int32 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *DraftPlayerRequest) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type UpdatePlayerRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId               int32    `protobuf:"varint,2,opt,name=teamId,proto3" json:"teamId,omitempty"`
	Rating               int32    `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePlayerRequest) Reset()         { *m = UpdatePlayerRequest{} }
func (m *UpdatePlayerRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePlayerRequest) ProtoMessage()    {}
func (*UpdatePlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerservice_320609145fc483eb, []int{2}
}
func (m *UpdatePlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlayerRequest.Unmarshal(m, b)
}
func (m *UpdatePlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlayerRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlayerRequest.Merge(dst, src)
}
func (m *UpdatePlayerRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePlayerRequest.Size(m)
}
func (m *UpdatePlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlayerRequest proto.InternalMessageInfo

func (m *UpdatePlayerRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePlayerRequest) GetTeamId() int32 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *UpdatePlayerRequest) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

type PlayerRequest struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerRequest) Reset()         { *m = PlayerRequest{} }
func (m *PlayerRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerRequest) ProtoMessage()    {}
func (*PlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerservice_320609145fc483eb, []int{3}
}
func (m *PlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerRequest.Unmarshal(m, b)
}
func (m *PlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerRequest.Marshal(b, m, deterministic)
}
func (dst *PlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerRequest.Merge(dst, src)
}
func (m *PlayerRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerRequest.Size(m)
}
func (m *PlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerRequest proto.InternalMessageInfo

func (m *PlayerRequest) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type PlayerResponse struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerResponse) Reset()         { *m = PlayerResponse{} }
func (m *PlayerResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerResponse) ProtoMessage()    {}
func (*PlayerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerservice_320609145fc483eb, []int{4}
}
func (m *PlayerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerResponse.Unmarshal(m, b)
}
func (m *PlayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerResponse.Marshal(b, m, deterministic)
}
func (dst *PlayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerResponse.Merge(dst, src)
}
func (m *PlayerResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerResponse.Size(m)
}
func (m *PlayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerResponse proto.InternalMessageInfo

func (m *PlayerResponse) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type AllPlayersRequest struct {
	TeamId               int32    `protobuf:"varint,1,opt,name=teamId,proto3" json:"teamId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllPlayersRequest) Reset()         { *m = AllPlayersRequest{} }
func (m *AllPlayersRequest) String() string { return proto.CompactTextString(m) }
func (*AllPlayersRequest) ProtoMessage()    {}
func (*AllPlayersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerservice_320609145fc483eb, []int{5}
}
func (m *AllPlayersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllPlayersRequest.Unmarshal(m, b)
}
func (m *AllPlayersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllPlayersRequest.Marshal(b, m, deterministic)
}
func (dst *AllPlayersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllPlayersRequest.Merge(dst, src)
}
func (m *AllPlayersRequest) XXX_Size() int {
	return xxx_messageInfo_AllPlayersRequest.Size(m)
}
func (m *AllPlayersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllPlayersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllPlayersRequest proto.InternalMessageInfo

func (m *AllPlayersRequest) GetTeamId() int32 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

type AllPlayersResponse struct {
	Players              []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AllPlayersResponse) Reset()         { *m = AllPlayersResponse{} }
func (m *AllPlayersResponse) String() string { return proto.CompactTextString(m) }
func (*AllPlayersResponse) ProtoMessage()    {}
func (*AllPlayersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerservice_320609145fc483eb, []int{6}
}
func (m *AllPlayersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllPlayersResponse.Unmarshal(m, b)
}
func (m *AllPlayersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllPlayersResponse.Marshal(b, m, deterministic)
}
func (dst *AllPlayersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllPlayersResponse.Merge(dst, src)
}
func (m *AllPlayersResponse) XXX_Size() int {
	return xxx_messageInfo_AllPlayersResponse.Size(m)
}
func (m *AllPlayersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllPlayersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllPlayersResponse proto.InternalMessageInfo

func (m *AllPlayersResponse) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func init() {
	proto.RegisterType((*Player)(nil), "go.micro.srv.playerservice.Player")
	proto.RegisterType((*DraftPlayerRequest)(nil), "go.micro.srv.playerservice.DraftPlayerRequest")
	proto.RegisterType((*UpdatePlayerRequest)(nil), "go.micro.srv.playerservice.UpdatePlayerRequest")
	proto.RegisterType((*PlayerRequest)(nil), "go.micro.srv.playerservice.PlayerRequest")
	proto.RegisterType((*PlayerResponse)(nil), "go.micro.srv.playerservice.PlayerResponse")
	proto.RegisterType((*AllPlayersRequest)(nil), "go.micro.srv.playerservice.AllPlayersRequest")
	proto.RegisterType((*AllPlayersResponse)(nil), "go.micro.srv.playerservice.AllPlayersResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PlayerService service

type PlayerServiceClient interface {
	Draft(ctx context.Context, in *DraftPlayerRequest, opts ...client.CallOption) (*PlayerResponse, error)
	Get(ctx context.Context, in *PlayerRequest, opts ...client.CallOption) (*PlayerResponse, error)
	Update(ctx context.Context, in *UpdatePlayerRequest, opts ...client.CallOption) (*PlayerResponse, error)
	GetAll(ctx context.Context, in *AllPlayersRequest, opts ...client.CallOption) (*AllPlayersResponse, error)
}

type playerServiceClient struct {
	c           client.Client
	serviceName string
}

func NewPlayerServiceClient(serviceName string, c client.Client) PlayerServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.playerservice"
	}
	return &playerServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *playerServiceClient) Draft(ctx context.Context, in *DraftPlayerRequest, opts ...client.CallOption) (*PlayerResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PlayerService.Draft", in)
	out := new(PlayerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) Get(ctx context.Context, in *PlayerRequest, opts ...client.CallOption) (*PlayerResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PlayerService.Get", in)
	out := new(PlayerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) Update(ctx context.Context, in *UpdatePlayerRequest, opts ...client.CallOption) (*PlayerResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PlayerService.Update", in)
	out := new(PlayerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) GetAll(ctx context.Context, in *AllPlayersRequest, opts ...client.CallOption) (*AllPlayersResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PlayerService.GetAll", in)
	out := new(AllPlayersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PlayerService service

type PlayerServiceHandler interface {
	Draft(context.Context, *DraftPlayerRequest, *PlayerResponse) error
	Get(context.Context, *PlayerRequest, *PlayerResponse) error
	Update(context.Context, *UpdatePlayerRequest, *PlayerResponse) error
	GetAll(context.Context, *AllPlayersRequest, *AllPlayersResponse) error
}

func RegisterPlayerServiceHandler(s server.Server, hdlr PlayerServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&PlayerService{hdlr}, opts...))
}

type PlayerService struct {
	PlayerServiceHandler
}

func (h *PlayerService) Draft(ctx context.Context, in *DraftPlayerRequest, out *PlayerResponse) error {
	return h.PlayerServiceHandler.Draft(ctx, in, out)
}

func (h *PlayerService) Get(ctx context.Context, in *PlayerRequest, out *PlayerResponse) error {
	return h.PlayerServiceHandler.Get(ctx, in, out)
}

func (h *PlayerService) Update(ctx context.Context, in *UpdatePlayerRequest, out *PlayerResponse) error {
	return h.PlayerServiceHandler.Update(ctx, in, out)
}

func (h *PlayerService) GetAll(ctx context.Context, in *AllPlayersRequest, out *AllPlayersResponse) error {
	return h.PlayerServiceHandler.GetAll(ctx, in, out)
}

func init() {
	proto.RegisterFile("proto/playerservice.proto", fileDescriptor_playerservice_320609145fc483eb)
}

var fileDescriptor_playerservice_320609145fc483eb = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xdf, 0x4b, 0xeb, 0x30,
	0x14, 0xbe, 0x6d, 0xb7, 0xde, 0x7b, 0x8f, 0x38, 0xf0, 0x08, 0xa3, 0xf6, 0x69, 0xe4, 0x69, 0x3a,
	0xcc, 0x60, 0xbe, 0x89, 0x2f, 0x03, 0x61, 0x0c, 0x44, 0x46, 0x75, 0x6f, 0x22, 0xd4, 0x35, 0x8e,
	0x40, 0xd7, 0xd6, 0x26, 0x0e, 0xfd, 0x97, 0xfc, 0x2b, 0x25, 0x49, 0x5b, 0x57, 0xe6, 0x46, 0xf5,
	0x2d, 0xdf, 0xb7, 0xf3, 0xfd, 0xc8, 0x4e, 0x0a, 0x27, 0x59, 0x9e, 0xca, 0x74, 0x98, 0xc5, 0xe1,
	0x3b, 0xcb, 0x05, 0xcb, 0xd7, 0x7c, 0xc1, 0xa8, 0xe6, 0xd0, 0x5f, 0xa6, 0x74, 0xc5, 0x17, 0x79,
	0x4a, 0x45, 0xbe, 0xa6, 0xb5, 0x09, 0xf2, 0x06, 0xee, 0x4c, 0x13, 0xd8, 0x01, 0x7b, 0x1a, 0x79,
	0x56, 0xcf, 0xea, 0xb7, 0x03, 0x7b, 0x1a, 0x61, 0x17, 0xdc, 0x7b, 0x16, 0xae, 0xa6, 0x91, 0x67,
	0x6b, 0xae, 0x40, 0x88, 0xd0, 0xba, 0x0d, 0x57, 0xcc, 0x73, 0x7a, 0x56, 0xff, 0x7f, 0xa0, 0xcf,
	0xe8, 0xc3, 0xbf, 0x59, 0x2a, 0xb8, 0xe4, 0x69, 0xe2, 0xb5, 0x34, 0x5f, 0x61, 0xe5, 0x13, 0x84,
	0x92, 0x27, 0x4b, 0xaf, 0x6d, 0x7c, 0x0c, 0x22, 0x0f, 0x80, 0xd7, 0x79, 0xf8, 0x2c, 0x4d, 0x7c,
	0xc0, 0x5e, 0x5e, 0x99, 0x90, 0xca, 0x3d, 0x51, 0xee, 0x96, 0x71, 0x57, 0x67, 0xe5, 0x20, 0x6b,
	0x4d, 0x0c, 0x52, 0xa9, 0x59, 0x99, 0x6a, 0xda, 0x54, 0x98, 0xcc, 0xe1, 0x78, 0x9e, 0x45, 0xa1,
	0x64, 0x75, 0xfb, 0x0e, 0xd8, 0xbc, 0xba, 0x24, 0x8f, 0x76, 0x5a, 0x77, 0xc1, 0xcd, 0x4d, 0x69,
	0xc7, 0xf0, 0x06, 0x91, 0x01, 0x1c, 0xd6, 0x0d, 0x55, 0x07, 0x4d, 0x54, 0xff, 0x5d, 0x85, 0xc9,
	0x0d, 0x74, 0xca, 0x61, 0x91, 0xa5, 0x89, 0x60, 0x78, 0x09, 0xae, 0xf9, 0x55, 0xcf, 0x1e, 0x8c,
	0x08, 0xdd, 0xbd, 0x1a, 0x5a, 0x68, 0x0b, 0x05, 0x19, 0xc0, 0xd1, 0x38, 0x8e, 0x0d, 0x29, 0xca,
	0xf8, 0xaf, 0xfe, 0xd6, 0x66, 0x7f, 0x12, 0x00, 0x6e, 0x0e, 0x17, 0xf1, 0x57, 0xf0, 0xb7, 0x88,
	0xf0, 0xac, 0x9e, 0xd3, 0x30, 0xbf, 0x94, 0x8c, 0x3e, 0x9c, 0xf2, 0xf2, 0x77, 0x66, 0x02, 0x19,
	0xb4, 0xf5, 0x0a, 0x91, 0xee, 0xf3, 0xd9, 0xde, 0xb2, 0x7f, 0xd6, 0x20, 0xb7, 0x28, 0x4d, 0xfe,
	0xe0, 0x23, 0x38, 0x13, 0x26, 0xf1, 0xb4, 0x89, 0xe8, 0x37, 0xfe, 0x4b, 0x70, 0xcd, 0x5b, 0xc1,
	0xe1, 0x3e, 0xdd, 0x37, 0xef, 0xe9, 0x87, 0x41, 0x1c, 0xdc, 0x09, 0x93, 0xe3, 0x38, 0xc6, 0xf3,
	0x7d, 0xba, 0xad, 0x35, 0xfb, 0xb4, 0xe9, 0x78, 0x19, 0xf5, 0xe4, 0xea, 0x4f, 0xff, 0xe2, 0x33,
	0x00, 0x00, 0xff, 0xff, 0x35, 0x0a, 0xb0, 0xb1, 0x17, 0x04, 0x00, 0x00,
}
